name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create buildozer.spec automatically
        run: |
          cat << 'EOF' > buildozer.spec
          [app]
          title = Bio Point
          package.name = biopoint
          package.domain = org.test
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas,txt
          version = 0.1
          requirements = python3,kivy==2.3.0

          android.api = 33
          android.minapi = 21
          android.ndk = 25b
          orientation = portrait
          fullscreen = 1
          android.archs = arm64-v8a
          android.allow_backup = True

          [buildozer]
          log_level = 1
          warn_on_root = 0
          EOF

      - name: Build APK using Official Buildozer Docker Container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/hostdir \
            -u root \
            kivy/buildozer \
            android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BioPoint-APK
          path: bin/*.apk
